name: pylops_diffusers_3090
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - cupy
  - cuda-version=11.8
  - pylops
  - pytorch-cuda=11.8 
  - torchvision
  - torchaudio
  - ipython
  - jupyter
  - torchinfo
  - diffusers
  - pip:
	- accelerate
