name: visualization
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - pip:
    - pyvista
