name: pylops_cupy_cusignal_3090
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.8
  - pip
  - numba==0.55.2
  - icc_rt
  - numpy
  - scipy>=1.4.0
  - pyfftw
  - pywavelets
  - matplotlib
  - ipython
  - jupyter
  - pip:
    - scikit-fmm
    - spgl1
