name: pylops_cupy_cusignal_3090
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - numba
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy>=1.4.0
  - cupy
  - cuda-version=11.4
  - cusignal
  - numba
  - icc_rt
  - pyfftw
  - pywavelets
  - matplotlib
  - ipython
  - jupyter
  - pip:
    - scikit-fmm
    - spgl1
